# yaml-language-server: $schema=https://json.schemastore.org/pnpm-workspace.json

minimumReleaseAge: 1441
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types'
  - '@cloudflare/workerd-*'
  - miniflare
  - wrangler
  - workerd

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

overrides:
  glob: latest
  minimatch: ^10.2.1
  flatted: ^3.4.2
  'esbuild@<0.28.1': '>=0.28.1'
  brace-expansion@<=5.0.7: ^5.0.8
  undici@>=7.0.0 <7.29.0: ^7.29.0
  nanoid@<3.3.18: ^3.3.18
