minimumReleaseAge: 1441
minimumReleaseAgeExclude:
  - '@cloudflare/worker-types'
  - '@cloudflare/workerd-*'
  - miniflare
  - wrangler
  - workerd

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

overrides:
  glob: latest
  minimatch: ^10.2.1
  flatted: ^3.4.2
  